language: ruby
cache: bundler
script: bundle exec jekyll build
deploy:
  provider: pages
  repo: elu00/elu00.github.io
  skip_cleanup: true
  local_dir: _site
  keep_history: true
  on:
    branch: master
