language: ruby
cache: bundler
script: bundle exec jekyll build
os: linux
dist: focal
deploy:
  strategy: git
  provider: pages
  repo: elu00/elu00.github.io
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: _site
  skip_cleanup: true
  cleanup: false
  keep_history: true
  on:
    branch: master
