language: ruby
cache: bundler
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: k0etJDNUN9/rZ9QHUqpEmHhR1xtPH6oOlkG3eI0qqvH5j1gdG7NzmxPkwJqsu/EKL7W0uQs7GYKgFaqXWt0FgIexW5lo4tExiwGko7TunlNadO78v4wNmi/ZBkKKZQEW1cpNSshiGeKqXmiVArfz7z4H3YDTChvVBqGFjNIS42X2LYLM/sq+Mse5YcPqLWduHN3aDk/GQUewIO1p/z9EaDmI3aCfIUeVtU/MdzTxGMvFvakr3avqB5ITgK29Z8J2ZcwxaFNek1fIhxTt+k2DIHXUp/+hbuoYe/8m+LqO7zGNNmEjOVOny1YJoBroKRhXbnHM2w0qMB5CGSiObidgTD0stIiN4Q5OgeQQ4xvmr0HS0+lyAdvy4IHpGbocRiRj1TIhbgn5bU38p7oYXa9qqT/KWJYOqTomYvvYn1OQ4uk8Ot24mkWrx4yOWjlWBqaEFY77A3V48j83bUSp9egbbUYbqbgD5fm1l8NV9Q8L7VuYurr2KnPrelvYyXJBzHVjjPX+n/2JqXYojzdzYkJ4Vrj2xF8hQ6dqQqgFjgPYiQ8Mo2HdvdAt2UxUMsjzNmPgoXRs2y14t2oNQwECp0i+l7mehHXll0H0ymOifUDBwawKzkS4Nf7VPlqlqbmxYXOVQYAELFmJNCMZ8Z4J3uRzxp5V0UgPXpAWCUC3KUbrD1Y=
